MERGIN_BASE_URL=
SECRET_KEY=
DB_USER=mergin
DB_PASSWORD=mergin
DB_DATABASE=mergin
DB_PORT=5432
COLLECT_STATISTICS=false
BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/0
